# Generated by Django 5.1.7 on 2025-05-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
