# Generated by Django 5.1.7 on 2025-05-22 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0002_categoria_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('descricao', models.TextField(max_length=300, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imagem', models.ImageField(unique=True, upload_to='fotos/produtos')),
                ('estoque', models.IntegerField()),
                ('disponivel', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
            ],
        ),
    ]
