# Generated by Django 5.1.7 on 2025-07-06 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinhos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caritem',
            old_name='car',
            new_name='carrinho',
        ),
    ]
