# Generated by Django 5.1.7 on 2025-07-10 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinhos', '0002_rename_car_caritem_carrinho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caritem',
            old_name='is_active',
            new_name='esta_disponivel',
        ),
    ]
