# Generated by Django 5.1.7 on 2025-07-10 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinhos', '0003_rename_is_active_caritem_esta_disponivel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caritem',
            options={'verbose_name': 'Item do Carrinho', 'verbose_name_plural': 'Itens do Carrinho'},
        ),
    ]
