# Generated by Django 5.1.7 on 2025-07-10 05:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinhos', '0004_alter_caritem_options'),
        ('produtos', '0002_alter_produto_options_alter_produto_estoque_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrinho',
            options={'verbose_name': 'Carrinho', 'verbose_name_plural': 'Carrinhos'},
        ),
        migrations.AddField(
            model_name='caritem',
            name='dados_personalizacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caritem',
            name='data_adicao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 10, 5, 7, 33, 110253, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caritem',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caritem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caritem',
            name='carrinho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrinhos.carrinho'),
        ),
        migrations.AlterField(
            model_name='caritem',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='caritem',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
